import smtplib
from email.message import EmailMessage
from datetime import datetime

from config.config import (
    EMAIL_SENDER,
    EMAIL_PASSWORD,
    EMAIL_RECEIVER,
    SMTP_SERVER,
    SMTP_PORT,
    PIPELINE_NAME,
)

from pipeline.logger import get_logger

logger = get_logger(__name__)


def send_email(
    start_time: datetime,
    end_time: datetime,
    records_processed: int,
    records_rejected: int,
    status: str,
    run_id: str | None = None,
    gold_tables_created: list[str] | None = None,
    database_status: str = "Successful",
    metadata_status: str = "Successful",
) -> None:
    """
    Sends pipeline execution report via email.
    """

    logger.info("Sending pipeline completion email...")

    duration = round(
        (end_time - start_time).total_seconds(), 2
    )

    subject = f"{PIPELINE_NAME} - {status}"

    gold_tables_created = gold_tables_created or []

    gold_tables_block = (
        "\n".join(f"    • {table}" for table in gold_tables_created)
        if gold_tables_created
        else "    (none)"
    )

    body = f"""
Pipeline Execution Report

Pipeline Name      : {PIPELINE_NAME}

Run ID              : {run_id or "N/A"}

Status             : {status}

Start Time         : {start_time}

End Time           : {end_time}

Execution Time     : {duration} Seconds

Records Processed  : {records_processed}

Rejected Records   : {records_rejected}

Gold Tables Created

{gold_tables_block}

Database Status     : {database_status}

Metadata Status      : {metadata_status}

Generated By       : Apache Airflow
"""

    message = EmailMessage()

    message["Subject"] = subject
    message["From"] = EMAIL_SENDER
    message["To"] = EMAIL_RECEIVER

    message.set_content(body)

    try:

        with smtplib.SMTP(
            SMTP_SERVER,
            SMTP_PORT,
        ) as smtp:

            smtp.starttls()

            smtp.login(
                EMAIL_SENDER,
                EMAIL_PASSWORD,
            )

            smtp.send_message(message)

        logger.info("Email sent successfully.")

    except Exception as e:

        logger.error(f"Email Failed : {e}")

        raise